In [18]:
import numpy as np
import random
import matplotlib.pyplot as plt

In [103]:
N = 5

# lista = np.array([random.choice([-1, 1]) for n in range(N**2)])
lista = np.array([n+1 for n in range(N**2)])
red = lista.reshape(N,N)
red

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [105]:
def matriz_aumentada(m, N):
    temp_list = []
    temp_list.append(np.concatenate([[red[N-1,N-1]], red[N-1], [red[N-1,0]]]))
    
    for i in range(N):
        temp_list.append(np.concatenate([[red[i,N-1]], red[i], [red[i,0]]]))
    
    temp_list.append(np.concatenate([[red[0,N-1]], red[0], [red[0,0]]]))
    return np.matrix(temp_list)
        
matriz_aumentada(red, N)

matrix([[25, 21, 22, 23, 24, 25, 21],
        [ 5,  1,  2,  3,  4,  5,  1],
        [10,  6,  7,  8,  9, 10,  6],
        [15, 11, 12, 13, 14, 15, 11],
        [20, 16, 17, 18, 19, 20, 16],
        [25, 21, 22, 23, 24, 25, 21],
        [ 5,  1,  2,  3,  4,  5,  1]])

In [155]:
def primeros_vecinos(m, N, i, j):
    M_a = matriz_aumentada(m, N) 
    A = (M_a[i-1:i+2, j-1:j+2])
    
    filtro = np.matrix([[1/np.sqrt(2)**3, 1, 1/np.sqrt(2)**3],
                    [1, 0, 1],
                    [1/np.sqrt(2)**3, 1, 1/np.sqrt(2)**3]])
    
    return np.multiply(A,filtro)

# matrix([[0.35355339, 1.        , 0.35355339],
#         [1.        , 0.        , 1.        ],
#         [0.35355339, 1.        , 0.35355339]])

primeros_vecinos(red, N, 1, 1)

matrix([[ 8.83883476, 21.        ,  7.77817459],
        [ 5.        ,  0.        ,  2.        ],
        [ 3.53553391,  6.        ,  2.47487373]])

In [160]:
def energia(m, N, i, j):
    vecinos = primeros_vecinos(m, N, i, j)
    E = vecinos * m[i-1,j-1]
    return np.sum(E)

energia(red, N, 1, 1)

56.62741699796952